server:
  port: 8888

spring:
  application:
    name: light-reading-cloud-config
  profiles:
      active: native
#      active: git
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/rep
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/